[profile.release]
debug = true

[package]
name = "paperclip"
version = "0.1.0"
authors = ["Craig Condon <craig.j.condon@gmail.com>"]
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "paperclip"
crate-type = ["cdylib"]

[dependencies]
matches = "0.1.8"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = { version = "1.0.44" }
crc = "1.8.1"
#jsonrpc-core = "14.0.5"
#jsonrpc-tcp-server = "14.0.5"
web-sys = "0.3.35"
console_error_panic_hook = "0.1.6"
#reqwest = "0.10.1"
#curl = "0.4.25"
futures = "0.3.1"
#path_abs = "0.5.0"
regex = "1.3.4"
to_absolute = "0.1.0"
js-sys = "0.3.35"
serde_derive = "1.0.104"

[dependencies.wasm-bindgen]
version = "^0.2"
features = ["serde-serialize"]
