name: Publish Packages
on:
  push:
    branches:
      - master
jobs:
  publish-packages:
    name: Publish NPM & Marketplaces
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: yarn install
      - run: yarn build
      - run: yarn publish:packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: "production"

      # wait for a bit for NPM packages to show up in registry
      - name: Sleep for a bit
        uses: jakejarvis/wait-action@master
        with:
          time: "120s"
      - run: yarn add vsce
      - run: npm publish:marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

          name: documentation
